"""Initial schema - multi-tenant tables

Revision ID: 846c3efa92ff
Revises: 
Create Date: 2025-12-19 17:30:30.523592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846c3efa92ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('xero_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('xero_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_xero_tenant_id'), 'organizations', ['xero_tenant_id'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('xero_contact_id', sa.String(length=255), nullable=True),
    sa.Column('chase_enabled', sa.Boolean(), nullable=False),
    sa.Column('chase_frequency_days', sa.Integer(), nullable=False),
    sa.Column('escalation_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_xero_contact_id'), 'clients', ['xero_contact_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('exclusion_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusion_rules_enabled'), 'exclusion_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_exclusion_rules_organization_id'), 'exclusion_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_exclusion_rules_rule_type'), 'exclusion_rules', ['rule_type'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('xero_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('xero_type', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('document_required', sa.Boolean(), nullable=False),
    sa.Column('document_received', sa.Boolean(), nullable=False),
    sa.Column('document_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_client_id'), 'transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_document_received'), 'transactions', ['document_received'], unique=False)
    op.create_index(op.f('ix_transactions_document_required'), 'transactions', ['document_required'], unique=False)
    op.create_index(op.f('ix_transactions_excluded'), 'transactions', ['excluded'], unique=False)
    op.create_index(op.f('ix_transactions_organization_id'), 'transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transactions_supplier_name'), 'transactions', ['supplier_name'], unique=False)
    op.create_index(op.f('ix_transactions_xero_transaction_id'), 'transactions', ['xero_transaction_id'], unique=True)
    op.create_table('xero_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('xero_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('xero_tenant_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('connected_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xero_connections_expires_at'), 'xero_connections', ['expires_at'], unique=False)
    op.create_index(op.f('ix_xero_connections_organization_id'), 'xero_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_xero_connections_xero_tenant_id'), 'xero_connections', ['xero_tenant_id'], unique=False)
    op.create_table('chases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('chase_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message_template', sa.String(length=255), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('magic_link_token', sa.String(length=255), nullable=True),
    sa.Column('magic_link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('magic_link_clicked', sa.Boolean(), nullable=False),
    sa.Column('magic_link_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('is_escalation', sa.Boolean(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chases_chase_type'), 'chases', ['chase_type'], unique=False)
    op.create_index(op.f('ix_chases_client_id'), 'chases', ['client_id'], unique=False)
    op.create_index(op.f('ix_chases_created_at'), 'chases', ['created_at'], unique=False)
    op.create_index(op.f('ix_chases_magic_link_token'), 'chases', ['magic_link_token'], unique=True)
    op.create_index(op.f('ix_chases_organization_id'), 'chases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chases_status'), 'chases', ['status'], unique=False)
    op.create_index(op.f('ix_chases_transaction_id'), 'chases', ['transaction_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('ocr_status', sa.String(length=50), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extracted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('extracted_supplier', sa.String(length=255), nullable=True),
    sa.Column('xero_file_id', sa.String(length=255), nullable=True),
    sa.Column('forwarded_to_xero', sa.Boolean(), nullable=False),
    sa.Column('forwarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_s3_key'), 'documents', ['s3_key'], unique=True)
    op.create_index(op.f('ix_documents_transaction_id'), 'documents', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_transaction_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_s3_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chases_transaction_id'), table_name='chases')
    op.drop_index(op.f('ix_chases_status'), table_name='chases')
    op.drop_index(op.f('ix_chases_organization_id'), table_name='chases')
    op.drop_index(op.f('ix_chases_magic_link_token'), table_name='chases')
    op.drop_index(op.f('ix_chases_created_at'), table_name='chases')
    op.drop_index(op.f('ix_chases_client_id'), table_name='chases')
    op.drop_index(op.f('ix_chases_chase_type'), table_name='chases')
    op.drop_table('chases')
    op.drop_index(op.f('ix_xero_connections_xero_tenant_id'), table_name='xero_connections')
    op.drop_index(op.f('ix_xero_connections_organization_id'), table_name='xero_connections')
    op.drop_index(op.f('ix_xero_connections_expires_at'), table_name='xero_connections')
    op.drop_table('xero_connections')
    op.drop_index(op.f('ix_transactions_xero_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_supplier_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_organization_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_excluded'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_document_required'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_document_received'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_client_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_exclusion_rules_rule_type'), table_name='exclusion_rules')
    op.drop_index(op.f('ix_exclusion_rules_organization_id'), table_name='exclusion_rules')
    op.drop_index(op.f('ix_exclusion_rules_enabled'), table_name='exclusion_rules')
    op.drop_table('exclusion_rules')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_xero_contact_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_organizations_xero_tenant_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
